### ISSUE TITLE
Script crashes on Cpt. K's Carved Archipelago due to too many towns

### ISSUE THREAD

**Issue by happysmash27** [F1rrel/RenewedVillageGrowth#136]
Is there any reason the limit is set at 1400 specifically and not, say, 2048? Currently the script crashes on Cpt. K's Carved Archipelago due to slightly too many towns usually being generated:
![2024-02-22-191149_2558x1987_scrot](https://github.com/F1rrel/RenewedVillageGrowth/assets/3620657/a34dd40e-678f-4e84-997a-b73e02007652)

This is despite me setting the number of towns to generate to the lowest amount able to be selected.

**Comment by F1rrel** [comment]
The number is deliberate based on the opcodes allowed for saving the game. With more than 1400 towns, the saving of all the data for the game script will take longer than the hardcoded limit and break the game. It would require removing some features or more optimizing the saving function to allow more towns on a map. However I would say the limit is sufficient for most playstyles.

You can specify a custom number of towns when starting a map, which will fix this problem.
