### ISSUE TITLE
Settings not corresponding with input values

### ISSUE THREAD

**Issue by matthijs8702** [F1rrel/RenewedVillageGrowth#138]
In my game  the script appears to be malfunctioning. As you can see in the screenshot below, settings are not corresponding with the input values and what is shown.

It is with version JGRPP 0.58.0

![image](https://github.com/F1rrel/RenewedVillageGrowth/assets/151522458/c63bab41-2606-4dd5-8eda-035f5c621424)

It may be an issue with JGRPP as i tried it with 0.56.2 and it seems to work.

**Comment by F1rrel** [comment]
Works correctly on 14.0 and JGRPP 0.58.3, so it seems to be already fixed in the newest versions.
