### ISSUE TITLE
BSPI support / industry generation awareness.

### ISSUE THREAD

**Issue by YellowOnion** [F1rrel/RenewedVillageGrowth#139]
BSPI with bit 2 set, requires power supplied to towns for secondary industries to function.

If the script could enforce power stations in every town that would be sweet, that way one could just setup ultra low spawn rates for everything and have a hard game that wasn't actually impossible.

Unless there's a better IO with similar mechanics that is already supported that you recommend?

**Comment by F1rrel** [comment]
This type of gameplay is very specific to only this BSPI economy with the bit 2 set, so I dont see a reason to add a dedicated feature to this script that would handle this edge case.

My suggested approach is to create a map in scenario editor and manually place a power plant next to every town. On a not that big map it should not take too long and you will get the gameplay style you seek.

Other option would be to create a small GS that would just place the power stations and then swap if for RVG in scenario editor, automating the funding.
