### ISSUE TITLE
Can't deliver food when using improved town industries 2.13

### ISSUE THREAD

**Issue by Farmer-Markus** [F1rrel/RenewedVillageGrowth#152]
I'm just using RenewedVillageGrowth(latest version) and iti 2.13 and towns with popularity bigger than 1000 wants food as category II. But the stations won't take food. When clicking with the openttd help symbol on a house in the town, there is no house taking food. Is this a bug or am I just stupid?

**Comment by F1rrel** [comment]
The Improved town industries may require ITL Houses NewGRF for modified town buildings. However I could not find it in the [notes with requirements](https://www.tt-forums.net/viewtopic.php?f=67&t=87332). With the ITL Houses, some town building do accept Food.

**Comment by Farmer-Markus** [comment]
Perfect thanks very much
