### ISSUE TITLE
FIRS4 cargoes stops counting after save/load on singleplayer

### ISSUE THREAD

**Issue by qamil95** [F1rrel/RenewedVillageGrowth#70]
In FIRS4 after saving and loading, cargoes are not counted as delivered. Attached zip file with .sav. Steps to reproduce:
1. Run new singleplayer game with FIRS4 steeltown (in my example - FIRS4 and PKP Set for cargoes only, no other grfs)
2. Create required bus/mail services between two towns
2. Transport second category cargo (local production) to any company in one of towns (in my case salt to Miechucino Mazowieckie)
3. Notice transported cargoes count in debug and town window (Miechucino Mazowieckie in my example)
4. Save game, back to main menu
5. Load game, new transport of salt would not be counted by town
I have added new platform to existing station, but it did not helped. Removed platform and recreated with the same name - no effect. Also tried to create station connected to different city and the same industry (station assigned to Bydgoszcz) - also no effect, so it suggests that it's something wrong with industry, and not station.

I'm reporting singleplayer issue, because that's where I noticed this problem. I can try also multiplayer to check whether it's also occuring, but not today.

Regards,
Kamil

[RVG_FIRS_Bug.zip](https://github.com/F1rrel/RenewedVillageGrowth/files/7281198/RVG_FIRS_Bug.zip)

**Comment by qamil95** [comment]
Tested multiplayer game, and it looks like after save/load on multiplayer, it works correctly. So it's singleplayer only issue.

**Comment by F1rrel** [comment]
Thanks for the detailed info, will check it out. I played FIRS4 IOTC and there were no issues.
