### ISSUE TITLE
Fails to initialize for SPIv1.3 industry set

### ISSUE THREAD

**Issue by VacuumBreather** [F1rrel/RenewedVillageGrowth#95]
The debug log shows it wrongly identifying the set as ECS Wood Vector 1.2 and then reports that it cannot create a procedural cargo list.
SPI = Stockpiled Industries.

**Comment by 2TallTyler** [comment]
I believe #94 should fix this.

**Comment by F1rrel** [comment]
Thanks for submitting the bug report, #94 fixes this issue.
